# databases:
#   - name:
#     plan: free
#     databaseName: tekplanit
#     user: tekplanit

services:
  - type: web
    plan: free
    name: hackindore-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: wddOGQDODBGegaJvpzAUleDgmfDmkoZn
      - key: DB_HOST
        value: viaduct.proxy.rlwy.net
      - key: DB_PORT
        value: 10459
      - key: EMAIL_HOST_USER
        value: tanyakemkar@thebollyweds.com
      - key: EMAIL_HOST_PASSWORD
        value: bewg mpxk pgnr ysdk
      - key: FRONTEND_URL
        value: https://tekplanit-frontend.vercel.app
      - key: BACKEND_URL
        value: http://localhost:8000
      - key: DEBUG
        value: "True"
        # fromDatabase:
        #   name: tekplanitdb
        #   property: connectionString
      - key: SECRET_KEY
        generateValue: true
